version: "3"

services:
  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - 10.0.0.1:80:80
      - 10.0.0.1:443:443
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./letsencrypt:/var/www/html:ro

  acme:
    build: .
    environment:
      - DOMAIN=example.com
      - AUTODNS_USER=invalid-user
      - AUTODNS_PASSWORD=secret
      - AUTODNS_CONTEXT=4
    restart: always
    volumes:
      - ./letsencrypt:/letsencrypt
