version: '3'

services:
  traefik:
    image: traefik
    command:
      --providers.docker
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.web.http.redirections.entrypoint.to=websecure
      --entrypoints.web.http.redirections.entrypoint.scheme=https
      --certificatesresolvers.letsencrypt.acme.email=""
      --certificatesresolvers.letsencrypt.acme.storage=acme.json
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # --accesslog=true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json

  web:
    build: .
    restart: always
    labels:
      - "traefik.http.routers.www.rule=Host(`www.example.com`) || Host(`example.com`)"
      - traefik.http.routers.www.tls=true
      - traefik.http.routers.www.tls.certresolver=letsencrypt
    links:
      - traefik
    volumes:
      - php:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 'wordpress_secret_password'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - db:/var/lib/mysql

volumes:
  php:
  db:
