version: "3"

services:
  traefik:
    image: traefik
    command: --providers.docker
    networks:
      default:
      wireguard_nextcloud:
        ipv4_address: 100.64.0.3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
      - ./traefik.yml:/traefik.yml

  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_secret_root
      - MYSQL_PASSWORD=db_secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: .
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=db_secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=secret
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.example.com
      - OVERWRITEPROTOCOL=https

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.example.com`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=lets-encrypt

networks:
  wireguard_nextcloud:
    external: true

volumes:
  nextcloud:
  apps:
  config:
  data:
  db:
