version: "3"

services:
  traefik:
    image: traefik
    command: --providers.docker
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./static.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic/traefik.yml
      - /data/tls/fullchain.pem:/etc/traefik/fullchain.pem
      - /data/tls/privkey.pem:/etc/traefik/privkey.pem
  app:
    image: vaultwarden/server
    restart: always
    labels:
      - traefik.http.routers.app.rule=Host(`vaultwarden.example.com`)
      - "traefik.http.routers.app.tls=true"
    volumes:
      - /data/vaultwarden:/data
    environment:
      DOMAIN: https://vaultwarden.example.com/
      SMTP_HOST: mail.example.com
      SMTP_FROM: vaultwarden@example.com
      #SMTP_PORT: 587
      #SMTP_SSL: "true"
      #SMTP_USERNAME: <username>
      #SMTP_PASSWORD: <password>
