entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'

certificatesResolvers:
  lets-encrypt:
    acme:
      storage: acme.json
      tlsChallenge: {}

providers:
  docker:
    watch: true

global:
  sendAnonymousUsage: false
