secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

services:
  db:
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - com.centurylinklabs.watchtower.enable=true
    secrets:
      - db_password
      - db_root_password

  traefik:
    image: traefik
    command:
      --providers.docker.exposedByDefault=false
      --entryPoints.web.address=:80
      #--certificatesresolvers.letsencrypt.acme.email=""
      #--certificatesresolvers.letsencrypt.acme.storage=/acme.json
      #--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      #--entryPoints.websecure.address=:443
    restart: always
    ports:
      - 7000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./acme.json:/acme.json

  redis:
    image: redis:alpine
    restart: always

  cron:
    image: nextcloud:${NEXTCLOUD_RELEASE}
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./volumes/apps:/var/www/html/custom_apps
      - ./volumes/config:/var/www/html/config
      - ./volumes/data:/var/www/html/data
    entrypoint: /cron.sh

  app:
    image: nextcloud:${NEXTCLOUD_RELEASE}
    restart: always
    depends_on:
      - db
      - redis
      - traefik
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./volumes/apps:/var/www/html/custom_apps
      - ./volumes/config:/var/www/html/config
      - ./volumes/data:/var/www/html/data
      - ./lib.sh:/docker-entrypoint-hooks.d/lib.sh
      - ./post-installation:/docker-entrypoint-hooks.d/post-installation
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/db_password
      - NEXTCLOUD_ADMIN_USER=admin
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
      #- OVERWRITEPROTOCOL=https
      - REDIS_HOST=redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      #- traefik.http.routers.nextcloud.tls=true
      #- traefik.http.routers.nextcloud.tls.certresolver=letsencrypt
      - com.centurylinklabs.watchtower.enable=true
    secrets:
      - db_password
