version: "3"

services:
  radius:
    build: .
    ports: 
      - "1812-1813:1812-1813/udp"
    volumes:
      - ./raddb/clients.conf:/etc/raddb/clients.conf
      - ./raddb/server.pem:/etc/raddb/certs/server.pem
      - ./raddb/ca.pem:/etc/raddb/certs/ca.pem
      - ./raddb/dh:/etc/raddb/certs/dh
      - ./raddb/mods-config/files/authorize:/etc/raddb/mods-config/files/authorize
