- name: Deploy nextcloud
  hosts: all
  user: root

  vars:
    project_root: /srv/docker/containers/nextcloud
    git_base: https://raw.githubusercontent.com/majes-git/docker/master/nextcloud-docker-host

  tasks:
    - name: Install required packages
      package:
        name:
          - python3-docker
        state: latest

    - name: Create project directory
      file:
        path: "{{ project_root }}"
        state: directory

    - name: Create nextcloud project file
      copy:
        dest: "{{ project_root }}/docker-compose.yaml"
        content: |
          version: "3"

          services:
            db:
              image: mariadb
              restart: always
              command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
              volumes:
                - db:/var/lib/mysql
              env_file: nextcloud.env
              environment:
                - MYSQL_DATABASE=nextcloud
                - MYSQL_USER=nextcloud

            app:
              image: nextcloud:fpm
              restart: always
              links:
                - db
              volumes:
                - nextcloud:/var/www/html
                - apps:/var/www/html/apps
                - config:/var/www/html/config
                - data:/var/www/html/data
              env_file: nextcloud.env
              environment:
                - MYSQL_DATABASE=nextcloud
                - MYSQL_USER=nextcloud
                - MYSQL_HOST=db
                - NEXTCLOUD_ADMIN_USER=admin
                - OVERWRITEPROTOCOL=https

            nginx-proxy:
              image: nginxproxy/nginx-proxy:alpine
              volumes:
                - /var/run/docker.sock:/tmp/docker.sock:ro
                - ./nginx.conf:/etc/nginx/nginx.conf:ro
                - /etc/tls:/etc/tls:ro
              restart: always
              ports:
                - 80:80
                - 443:443
              links:
                - app
              volumes_from:
                - app

          volumes:
            nextcloud:
            apps:
            config:
            data:
            db:

    - name: Copy nextcloud environment file
      copy:
        src: nextcloud.env
        dest: "{{ project_root }}/nextcloud.env"

    - name: Download nginx.conf
      get_url:
        url: "{{ git_base }}/nginx.conf"
        dest: "{{ project_root }}/nginx.conf"

    - name: Create and start services
      docker_compose:
        project_src: "{{ project_root }}"
      register: output

    - name: Copy ldap environment file
      copy:
        src: ldap.env
        dest: "{{ project_root }}/ldap.env"

    - name: Download nextcloud prepare script
      get_url:
        url: "{{ git_base }}/prepare-nextcloud.bash"
        dest: "{{ project_root }}/prepare-nextcloud.bash"
        mode: '755'

    - name: Run nextcloud prepare script
      command: "{{ project_root }}/prepare-nextcloud.bash"
