- name: Deploy nextcloud
  hosts: all
  user: root

  vars:
    hostname: nextcloud.example.com
    project_root: /srv/docker/containers/nextcloud
    git_base: https://raw.githubusercontent.com/majes-git/docker/master/nextcloud-docker-host
    admin_password: admin_secret
    db_password: db_secret
    db_root_password: db_root_secret

  tasks:
    - name: Install required packages
      package:
        name:
          - python3-docker
        state: latest

    - name: Create project directory
      file:
        path: "{{ project_root }}"
        state: directory

    - name: Create nextcloud project file
      copy:
        dest: "{{ project_root }}/docker-compose.yaml"
        content: |
          version: "3"

          services:
            db:
              image: mariadb
              restart: always
              command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
              volumes:
                - db:/var/lib/mysql
              environment:
                - MYSQL_ROOT_PASSWORD={{ db_root_password }}
                - MYSQL_PASSWORD={{ db_password }}
                - MYSQL_DATABASE=nextcloud
                - MYSQL_USER=nextcloud

            app:
              image: nextcloud:fpm
              restart: always
              links:
                - db
              volumes:
                - nextcloud:/var/www/html
                - apps:/var/www/html/apps
                - config:/var/www/html/config
                - data:/var/www/html/data
              environment:
                - MYSQL_PASSWORD={{ db_password }}
                - MYSQL_DATABASE=nextcloud
                - MYSQL_USER=nextcloud
                - MYSQL_HOST=db
                - NEXTCLOUD_ADMIN_USER=admin
                - NEXTCLOUD_ADMIN_PASSWORD={{ admin_password }}
                - NEXTCLOUD_TRUSTED_DOMAINS={{ hostname }}
                - OVERWRITEPROTOCOL=https

            nginx-proxy:
              image: nginxproxy/nginx-proxy:alpine
              volumes:
                - /var/run/docker.sock:/tmp/docker.sock:ro
                - ./nginx.conf:/etc/nginx/nginx.conf:ro
                - /etc/tls:/etc/tls:ro
              restart: always
              ports:
                - 80:80
                - 443:443
              links:
                - app
              volumes_from:
                - app

          volumes:
            nextcloud:
            apps:
            config:
            data:
            db:

    - name: Download nginx.conf
      get_url:
        url: "{{ git_base }}/nginx.conf"
        dest: "{{ project_root }}/nginx.conf"

    - name: Create and start services
      docker_compose:
        project_src: "{{ project_root }}"
      register: output
