version: "3"

services:
  traefik:
    image: traefik
    command:
      --providers.docker.exposedByDefault=false
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --certificatesresolvers.letsencrypt.acme.email=""
      --certificatesresolvers.letsencrypt.acme.storage=acme.json
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      #--accesslog=true
      #--api.insecure=true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    # in case there is another reverse-proxy in front of us,
    # use something like this:
    # networks:
    #   default:
    #   nginx:
    #     aliases:
    #       - vpn1.example.com

  # data-sync:
  #   build: data-sync
  #   restart: always
  #   environment:
  #     - SYNC_TARGET=vpn2.example.com
  #     - SYNC_SYNC_SSH_PORT=2222
  #   volumes:
  #     - ./data:/data:ro
  #     - ./sites.yaml:/sites.yaml:ro
  #     - ./known_hosts_vpn2:/root/.ssh/known_hosts:ro
  #     - ./id_rsa_vpn2:/root/.ssh/id_rsa:ro
