version: "3"

services:
  wireguard:
    build: .
    container_name: wireguard
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820/udp
      #- 80:80
      #- 443:443
    environment:
      - IP_ADDRESS=10.0.0.1/24
      - PRIVATE_KEY=ABCDEF...
      - PEERS=10.0.0.2/32:ZYXWVU... 10.0.0.3/32:TSRQPO... 
      - KEEPALIVE=25
      # uncomment on wireguard client
      #- ENDPOINT=vpn.example.com:51820
      # uncomment on wireguard server, if portforwarding is wanted
      #- IPTABLES=iptables -t nat -A PREROUTING -p tcp --match multiport --dports 80,443 -j DNAT --to 10.0.0.2; iptables -t nat -A POSTROUTING -p tcp --match multiport --dports 80,443 -o wg0 -j MASQUERADE
